name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: JWTSecret
      run: php artisan jwt:secret
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        JWT_SECRET: uZfUpRMRzY5uXVQjtbqZBC4AQUBH6hTIvZEtfpoxozzY6hYq44XDxTQZV9UtXyOq
      run: vendor/bin/phpunit
